name: 💡 Feature Request
description: Suggest a new feature or improvement for ProLava
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature description
      description: Explain your idea clearly.
      placeholder: What would you like to add?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this needed?
      description: Explain why this feature is useful.
    validations:
      required: false
      
