name: ❓ Question
description: Ask a question about ProLava
title: "[QUESTION]: "
labels: ["question"]
body:
  - type: textarea
    attributes:
      label: Your question
      description: Ask clearly and provide context.
    validations:
      required: true
      
